require("plugins.copilot")
require("plugins.gitsigns")
require("plugins.mini")
require("plugins.fzf")
require("plugins.nvim-tree")
require("plugins.treesitter")
require("plugins.lspconfig")
require("plugins.beauwilliams-statusline")
require("plugins.colorschemes")
-- require("plugins.luasnip")
