# PATH
typeset -U path    # remove duplicates, keep first occurrence
path=(
  "$HOME/.local/bin"
  "$HOME/scripts"
  "$HOME/.krew/bin"
  "$HOME/.config/emacs/bin"
  "$HOME/.config/emacs/bin"
  "$HOME/go/bin"
  "$HOME/.bun/bin"
  #"$HOME/.volta/bin"
  $path
)
export PATH

# -- History
export HISTFILE=$HOME/.zhistory
export HISTSIZ=5000
export SAVEHIST=$HISTSIZE
export HISTDUP=erase

# -- fzf
# - theme
fg="#CBE0F0"
bg="#011628"
bg_highlight="#143652"
purple="#B388FF"
blue="#06BCE4"
cyan="#2CF9ED"
export FZF_DEFAULT_OPTS="--color=fg:${fg},hl:${purple},fg+:${fg},hl+:${purple},info:${blue},prompt:${cyan},pointer:${cyan},marker:${cyan},spinner:${cyan},header:${cyan}"
export FZF_DEFAULT_COMMAND="fd --hidden --strip-cwd-prefix --exclude .git"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd --type=d --hidden --strip-cwd-prefix --exclude .git"
export FZF_CTRL_T_OPTS="--preview '$show_file_or_dir_preview'"
export FZF_ALT_C_OPTS="--preview 'eza --tree --color=always {} | head -200'"

# Everything else
export BAT_THEME=tokyonight_night
export EDITOR=nvim

[[ -f $HOME/.zshenv.local ]] && source $HOME/.zshenv.local
